# Generated by Django 3.0.3 on 2020-03-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=5000)),
                ('date_post', models.IntegerField()),
                ('html_description', models.TextField()),
            ],
        ),
    ]
