# Generated by Django 3.0.3 on 2020-03-07 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0002_auto_20200305_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('html_description', models.TextField()),
                ('link', models.CharField(max_length=5000)),
                ('applied', models.DateTimeField()),
                ('interview', models.DateTimeField()),
                ('status', models.CharField(max_length=40)),
                ('note', models.CharField(max_length=255)),
                ('skills', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
