# Generated by Django 3.0.3 on 2020-03-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='applied',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='interview',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
