# Generated by Django 3.0.3 on 2020-03-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20200307_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
